//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFN_Switcher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Standard-Kennung")]
        public string Nickname {
            get {
                return ((string)(this["Nickname"]));
            }
            set {
                this["Nickname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GatewayActivated {
            get {
                return ((bool)(this["GatewayActivated"]));
            }
            set {
                this["GatewayActivated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public decimal WaitForConnectSeconds {
            get {
                return ((decimal)(this["WaitForConnectSeconds"]));
            }
            set {
                this["WaitForConnectSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal UseServer2AfterNumberOfFailedReconnects {
            get {
                return ((decimal)(this["UseServer2AfterNumberOfFailedReconnects"]));
            }
            set {
                this["UseServer2AfterNumberOfFailedReconnects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ComportEnabled {
            get {
                return ((bool)(this["ComportEnabled"]));
            }
            set {
                this["ComportEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RTS {
            get {
                return ((bool)(this["RTS"]));
            }
            set {
                this["RTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal Comport {
            get {
                return ((decimal)(this["Comport"]));
            }
            set {
                this["Comport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal DelaySeconds {
            get {
                return ((decimal)(this["DelaySeconds"]));
            }
            set {
                this["DelaySeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public decimal DelayAfterSendingMilliSeconds {
            get {
                return ((decimal)(this["DelayAfterSendingMilliSeconds"]));
            }
            set {
                this["DelayAfterSendingMilliSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public decimal WatchdogMinutes {
            get {
                return ((decimal)(this["WatchdogMinutes"]));
            }
            set {
                this["WatchdogMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoReconnect {
            get {
                return ((bool)(this["AutoReconnect"]));
            }
            set {
                this["AutoReconnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public decimal WaitPenaltyMinutes {
            get {
                return ((decimal)(this["WaitPenaltyMinutes"]));
            }
            set {
                this["WaitPenaltyMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FlagChannelCommanderWhenSending {
            get {
                return ((bool)(this["FlagChannelCommanderWhenSending"]));
            }
            set {
                this["FlagChannelCommanderWhenSending"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WhenMovedToOtherChannelOutputMute {
            get {
                return ((bool)(this["WhenMovedToOtherChannelOutputMute"]));
            }
            set {
                this["WhenMovedToOtherChannelOutputMute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public decimal NumberOfChecksIfTeamspeakIsLying {
            get {
                return ((decimal)(this["NumberOfChecksIfTeamspeakIsLying"]));
            }
            set {
                this["NumberOfChecksIfTeamspeakIsLying"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JumpBackToChannelAfterWaitPenaltyMinutes {
            get {
                return ((bool)(this["JumpBackToChannelAfterWaitPenaltyMinutes"]));
            }
            set {
                this["JumpBackToChannelAfterWaitPenaltyMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("voice.ts-ffn.com")]
        public string TSServer1_ServerURL {
            get {
                return ((string)(this["TSServer1_ServerURL"]));
            }
            set {
                this["TSServer1_ServerURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FFN-Switcher")]
        public string TSServer1_LoginName {
            get {
                return ((string)(this["TSServer1_LoginName"]));
            }
            set {
                this["TSServer1_LoginName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TSServer1_Password {
            get {
                return ((string)(this["TSServer1_Password"]));
            }
            set {
                this["TSServer1_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal TSServer1_ChannelID {
            get {
                return ((decimal)(this["TSServer1_ChannelID"]));
            }
            set {
                this["TSServer1_ChannelID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TSServer1_ChannelPW {
            get {
                return ((string)(this["TSServer1_ChannelPW"]));
            }
            set {
                this["TSServer1_ChannelPW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TSServer1_WhisperBlocked {
            get {
                return ((bool)(this["TSServer1_WhisperBlocked"]));
            }
            set {
                this["TSServer1_WhisperBlocked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TSServer1_AlwaysChannelCommander {
            get {
                return ((bool)(this["TSServer1_AlwaysChannelCommander"]));
            }
            set {
                this["TSServer1_AlwaysChannelCommander"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("voice.ts-ffn.com")]
        public string TSServer2_ServerURL {
            get {
                return ((string)(this["TSServer2_ServerURL"]));
            }
            set {
                this["TSServer2_ServerURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FFN-Switcher")]
        public string TSServer2_LoginName {
            get {
                return ((string)(this["TSServer2_LoginName"]));
            }
            set {
                this["TSServer2_LoginName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TSServer2_Password {
            get {
                return ((string)(this["TSServer2_Password"]));
            }
            set {
                this["TSServer2_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal TSServer2_ChannelID {
            get {
                return ((decimal)(this["TSServer2_ChannelID"]));
            }
            set {
                this["TSServer2_ChannelID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TSServer2_ChannelPW {
            get {
                return ((string)(this["TSServer2_ChannelPW"]));
            }
            set {
                this["TSServer2_ChannelPW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TSServer2_WhisperBlocked {
            get {
                return ((bool)(this["TSServer2_WhisperBlocked"]));
            }
            set {
                this["TSServer2_WhisperBlocked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TSServer2_AlwaysChannelCommander {
            get {
                return ((bool)(this["TSServer2_AlwaysChannelCommander"]));
            }
            set {
                this["TSServer2_AlwaysChannelCommander"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8080")]
        public decimal WebserverTCPPort {
            get {
                return ((decimal)(this["WebserverTCPPort"]));
            }
            set {
                this["WebserverTCPPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string WebserverListeningIP {
            get {
                return ((string)(this["WebserverListeningIP"]));
            }
            set {
                this["WebserverListeningIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./www")]
        public string WebserverDocumentRoot {
            get {
                return ((string)(this["WebserverDocumentRoot"]));
            }
            set {
                this["WebserverDocumentRoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WebserverVerboseLogging {
            get {
                return ((bool)(this["WebserverVerboseLogging"]));
            }
            set {
                this["WebserverVerboseLogging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartTeamspeakClientAtStartup {
            get {
                return ((bool)(this["StartTeamspeakClientAtStartup"]));
            }
            set {
                this["StartTeamspeakClientAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:/Programme/Teamspeak2_RC2/TeamSpeak.exe")]
        public string TeamspeakClientURL {
            get {
                return ((string)(this["TeamspeakClientURL"]));
            }
            set {
                this["TeamspeakClientURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ffn-switcher.log")]
        public string Logfile {
            get {
                return ((string)(this["Logfile"]));
            }
            set {
                this["Logfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LogToFileEnabled {
            get {
                return ((bool)(this["LogToFileEnabled"]));
            }
            set {
                this["LogToFileEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogToScreenEnabled {
            get {
                return ((bool)(this["LogToScreenEnabled"]));
            }
            set {
                this["LogToScreenEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./beacon/gateway.wav")]
        public string GatewayBeaconFile {
            get {
                return ((string)(this["GatewayBeaconFile"]));
            }
            set {
                this["GatewayBeaconFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MuteOutputWhenPlayingBeacon {
            get {
                return ((bool)(this["MuteOutputWhenPlayingBeacon"]));
            }
            set {
                this["MuteOutputWhenPlayingBeacon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReplayGatewayBeacon {
            get {
                return ((bool)(this["ReplayGatewayBeacon"]));
            }
            set {
                this["ReplayGatewayBeacon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReplayGatewayBeaconOnlyWhenActivity {
            get {
                return ((bool)(this["ReplayGatewayBeaconOnlyWhenActivity"]));
            }
            set {
                this["ReplayGatewayBeaconOnlyWhenActivity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public decimal GatewayBeaconReplayInMinutes {
            get {
                return ((decimal)(this["GatewayBeaconReplayInMinutes"]));
            }
            set {
                this["GatewayBeaconReplayInMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public decimal MaximumBeaconPlayTimeSeconds {
            get {
                return ((decimal)(this["MaximumBeaconPlayTimeSeconds"]));
            }
            set {
                this["MaximumBeaconPlayTimeSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./beacon/connect.wav")]
        public string ConnectFile {
            get {
                return ((string)(this["ConnectFile"]));
            }
            set {
                this["ConnectFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayAtConnect {
            get {
                return ((bool)(this["PlayAtConnect"]));
            }
            set {
                this["PlayAtConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayAtDisconnect {
            get {
                return ((bool)(this["PlayAtDisconnect"]));
            }
            set {
                this["PlayAtDisconnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./beacon/disconnect.wav")]
        public string DisconnectFile {
            get {
                return ((string)(this["DisconnectFile"]));
            }
            set {
                this["DisconnectFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./beacon/gateway_disabled.wav")]
        public string GatewayDisabledFile {
            get {
                return ((string)(this["GatewayDisabledFile"]));
            }
            set {
                this["GatewayDisabledFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayWhenDisabled {
            get {
                return ((bool)(this["PlayWhenDisabled"]));
            }
            set {
                this["PlayWhenDisabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./beacon/rogerbeep.wav")]
        public string RogerBeepFile {
            get {
                return ((string)(this["RogerBeepFile"]));
            }
            set {
                this["RogerBeepFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayRogerBeep {
            get {
                return ((bool)(this["PlayRogerBeep"]));
            }
            set {
                this["PlayRogerBeep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./beacon/gateway_offline.wav")]
        public string GatewayOfflineFile {
            get {
                return ((string)(this["GatewayOfflineFile"]));
            }
            set {
                this["GatewayOfflineFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayWhenOffline {
            get {
                return ((bool)(this["PlayWhenOffline"]));
            }
            set {
                this["PlayWhenOffline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public decimal AutoReconnectSeconds {
            get {
                return ((decimal)(this["AutoReconnectSeconds"]));
            }
            set {
                this["AutoReconnectSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SetupWizardDone {
            get {
                return ((bool)(this["SetupWizardDone"]));
            }
            set {
                this["SetupWizardDone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LicenseAccepted {
            get {
                return ((bool)(this["LicenseAccepted"]));
            }
            set {
                this["LicenseAccepted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Wizard_Step2_Done {
            get {
                return ((bool)(this["Wizard_Step2_Done"]));
            }
            set {
                this["Wizard_Step2_Done"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Wizard_Step3_Done {
            get {
                return ((bool)(this["Wizard_Step3_Done"]));
            }
            set {
                this["Wizard_Step3_Done"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Wizard_Step4_Done {
            get {
                return ((bool)(this["Wizard_Step4_Done"]));
            }
            set {
                this["Wizard_Step4_Done"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Wizard_Step5_Done {
            get {
                return ((bool)(this["Wizard_Step5_Done"]));
            }
            set {
                this["Wizard_Step5_Done"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Wizard_Step6_Done {
            get {
                return ((bool)(this["Wizard_Step6_Done"]));
            }
            set {
                this["Wizard_Step6_Done"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Wizard_Step7_Done {
            get {
                return ((bool)(this["Wizard_Step7_Done"]));
            }
            set {
                this["Wizard_Step7_Done"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Wizard_Step8_Done {
            get {
                return ((bool)(this["Wizard_Step8_Done"]));
            }
            set {
                this["Wizard_Step8_Done"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Wizard_Step9_Done {
            get {
                return ((bool)(this["Wizard_Step9_Done"]));
            }
            set {
                this["Wizard_Step9_Done"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Wizard_Step10_Done {
            get {
                return ((bool)(this["Wizard_Step10_Done"]));
            }
            set {
                this["Wizard_Step10_Done"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotifyIfSpeakPauseFail {
            get {
                return ((bool)(this["NotifyIfSpeakPauseFail"]));
            }
            set {
                this["NotifyIfSpeakPauseFail"] = value;
            }
        }
    }
}
